[2025-07-30T00:00:02.107+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-29T00:00:00+00:00 [queued]>
[2025-07-30T00:00:02.129+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-29T00:00:00+00:00 [queued]>
[2025-07-30T00:00:02.129+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-30T00:00:02.148+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_from_minio> on 2025-07-29 00:00:00+00:00
[2025-07-30T00:00:02.158+0000] {standard_task_runner.py:60} INFO - Started process 45833 to run task
[2025-07-30T00:00:02.162+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sales_batch_etl', 'load_from_minio', 'scheduled__2025-07-29T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/sales_batch_etl.py', '--cfg-path', '/tmp/tmp05l3fqa8']
[2025-07-30T00:00:02.191+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask load_from_minio
[2025-07-30T00:00:02.450+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-30T00:00:02.716+0000] {task_command.py:423} INFO - Running <TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-29T00:00:00+00:00 [running]> on host e17dc2585651
[2025-07-30T00:00:03.063+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_batch_etl' AIRFLOW_CTX_TASK_ID='load_from_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-29T00:00:00+00:00'
[2025-07-30T00:00:03.071+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-30T00:00:03.077+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/load_from_minio.py']
[2025-07-30T00:00:03.159+0000] {subprocess.py:86} INFO - Output:
[2025-07-30T00:00:04.916+0000] {subprocess.py:93} INFO - ‚è≥ Connecting to MinIO...
[2025-07-30T00:00:04.922+0000] {subprocess.py:93} INFO - üì• Downloading 'sales.csv' from bucket 'raw'
[2025-07-30T00:00:04.924+0000] {subprocess.py:93} INFO - ‚úÖ Downloaded data with shape: (10000, 6)
[2025-07-30T00:00:04.924+0000] {subprocess.py:93} INFO - üìÅ Data saved to /tmp/sales.csv
[2025-07-30T00:00:04.978+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-30T00:00:05.040+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=sales_batch_etl, task_id=load_from_minio, execution_date=20250729T000000, start_date=20250730T000002, end_date=20250730T000005
[2025-07-30T00:00:05.097+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-30T00:00:05.152+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
