[2025-07-26T00:04:06.821+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-25T00:00:00+00:00 [queued]>
[2025-07-26T00:04:06.834+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-25T00:00:00+00:00 [queued]>
[2025-07-26T00:04:06.835+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-26T00:04:06.849+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_from_minio> on 2025-07-25 00:00:00+00:00
[2025-07-26T00:04:06.855+0000] {standard_task_runner.py:60} INFO - Started process 30273 to run task
[2025-07-26T00:04:06.861+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sales_batch_etl', 'load_from_minio', 'scheduled__2025-07-25T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/sales_batch_etl.py', '--cfg-path', '/tmp/tmpnfh4yhtk']
[2025-07-26T00:04:06.863+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask load_from_minio
[2025-07-26T00:04:06.897+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-26T00:04:06.943+0000] {task_command.py:423} INFO - Running <TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-25T00:00:00+00:00 [running]> on host e17dc2585651
[2025-07-26T00:04:07.050+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_batch_etl' AIRFLOW_CTX_TASK_ID='load_from_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T00:00:00+00:00'
[2025-07-26T00:04:07.053+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-26T00:04:07.055+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/load_from_minio.py']
[2025-07-26T00:04:07.075+0000] {subprocess.py:86} INFO - Output:
[2025-07-26T00:04:09.050+0000] {subprocess.py:93} INFO - ‚è≥ Connecting to MinIO...
[2025-07-26T00:04:09.054+0000] {subprocess.py:93} INFO - üì• Downloading 'sales.csv' from bucket 'raw'
[2025-07-26T00:04:09.054+0000] {subprocess.py:93} INFO - ‚úÖ Downloaded data with shape: (10000, 6)
[2025-07-26T00:04:09.054+0000] {subprocess.py:93} INFO - üìÅ Data saved to /tmp/sales.csv
[2025-07-26T00:04:09.167+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-26T00:04:09.237+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=sales_batch_etl, task_id=load_from_minio, execution_date=20250725T000000, start_date=20250726T000406, end_date=20250726T000409
[2025-07-26T00:04:09.307+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-26T00:04:09.354+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
