[2025-07-31T00:07:29.322+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-30T00:00:00+00:00 [queued]>
[2025-07-31T00:07:29.330+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-30T00:00:00+00:00 [queued]>
[2025-07-31T00:07:29.330+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-31T00:07:29.347+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_from_minio> on 2025-07-30 00:00:00+00:00
[2025-07-31T00:07:29.352+0000] {standard_task_runner.py:60} INFO - Started process 48690 to run task
[2025-07-31T00:07:29.356+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sales_batch_etl', 'load_from_minio', 'scheduled__2025-07-30T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/sales_batch_etl.py', '--cfg-path', '/tmp/tmp3_bs4i71']
[2025-07-31T00:07:29.359+0000] {standard_task_runner.py:88} INFO - Job 43: Subtask load_from_minio
[2025-07-31T00:07:29.379+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-31T00:07:29.423+0000] {task_command.py:423} INFO - Running <TaskInstance: sales_batch_etl.load_from_minio scheduled__2025-07-30T00:00:00+00:00 [running]> on host e17dc2585651
[2025-07-31T00:07:29.501+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_batch_etl' AIRFLOW_CTX_TASK_ID='load_from_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-30T00:00:00+00:00'
[2025-07-31T00:07:29.503+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-31T00:07:29.507+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/scripts/load_from_minio.py']
[2025-07-31T00:07:29.527+0000] {subprocess.py:86} INFO - Output:
[2025-07-31T00:07:30.870+0000] {subprocess.py:93} INFO - ‚è≥ Connecting to MinIO...
[2025-07-31T00:07:30.873+0000] {subprocess.py:93} INFO - üì• Downloading 'sales.csv' from bucket 'raw'
[2025-07-31T00:07:30.874+0000] {subprocess.py:93} INFO - ‚úÖ Downloaded data with shape: (10000, 6)
[2025-07-31T00:07:30.875+0000] {subprocess.py:93} INFO - üìÅ Data saved to /tmp/sales.csv
[2025-07-31T00:07:30.942+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-31T00:07:31.009+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=sales_batch_etl, task_id=load_from_minio, execution_date=20250730T000000, start_date=20250731T000729, end_date=20250731T000731
[2025-07-31T00:07:31.043+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-31T00:07:31.082+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
